version: '3.8'

services:
  backend:
    build: .
    container_name: tiemgram-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    environment:
      - NODE_ENV=production
